"""initial

Revision ID: 7a227a9b76b5
Revises: 
Create Date: 2024-11-05 16:23:05.973401

"""
from alembic import op
import sqlalchemy as sa

from project.core.config import settings


# revision identifiers, used by Alembic.
revision = '7a227a9b76b5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apartments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartment_number', sa.String().with_variant(sa.String(length=255), 'postgresql'), nullable=False),
    sa.Column('square_meters', sa.Float(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.Column('owner_price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema=settings.POSTGRES_SCHEMA
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apartments', schema=settings.POSTGRES_SCHEMA)
    # ### end Alembic commands ###